<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * `messenger_failed` existait deja sur les bases qui avaient vu passer un
 * echec : `auto_setup` valait `true` par defaut pour ce transport, alors que
 * `media` l'a explicitement a `false` depuis la tache 1. Cette migration
 * ferme l'ecart en creant la table par avance, comme toute autre table du
 * projet — plus question qu'elle depende de l'historique des echecs pour
 * exister.
 *
 * Le schema est copie de celui que `symfony/doctrine-messenger` genere
 * lui-meme (`Connection::buildSchemaTable()`), colonne par colonne et type
 * par type : c'est le contrat que `messenger:failed:*` lit et ecrit, pas une
 * table qu'on invente cote applicatif.
 */
final class Version20260726145716 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table messenger_failed geree par une migration explicite, plus par l\'auto-DDL du transport.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_failed (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body         TEXT NOT NULL,
                headers      TEXT NOT NULL,
                queue_name   VARCHAR(190) NOT NULL,
                created_at   TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // Meme quadruplet de colonnes que celui que le transport interroge pour
        // retrouver les messages disponibles d'une file : sans cet index, un
        // gros volume d'echecs ferait un balayage complet a chaque
        // `messenger:failed:show`.
        $this->addSql('CREATE INDEX messenger_failed_queue_idx ON messenger_failed (queue_name, available_at, delivered_at, id)');

        $this->comment('TABLE messenger_failed', "Messages definitivement en echec apres epuisement des tentatives du transport `media`. C'est le seul endroit ou un echec reste visible : `messenger:failed:show`/`:retry`/`:remove` le lisent et l'ecrivent, rien d'applicatif n'y touche.");
        $this->comment('COLUMN messenger_failed.id', "Identifiant technique du transport, sans rapport avec les ULID du reste du projet : cette table appartient a Messenger, pas a un contexte metier.");
        $this->comment('COLUMN messenger_failed.body', "Enveloppe serialisee du message d'origine (le ProcessMediaCommand qui a echoue). Jamais lu directement : `messenger:failed:show` le deserialise.");
        $this->comment('COLUMN messenger_failed.headers', "En-tetes de transport serialises (nom de la classe, timestamps de tentative, etc.), necessaires pour rejouer le message avec `messenger:failed:retry`.");
        $this->comment('COLUMN messenger_failed.queue_name', "Nom du transport d'origine du message avant son echec, ici toujours 'media'. Permet a terme d'accueillir l'echec d'un second transport dans la meme table.");
        $this->comment('COLUMN messenger_failed.created_at', "Instant ou le message est arrive dans le transport d'echec, c'est-a-dire l'instant de l'echec definitif.");
        $this->comment('COLUMN messenger_failed.available_at', "Instant a partir duquel le message est eligible a une nouvelle tentative. Egal a created_at ici : ce transport ne reessaie pas de lui-meme, seul `messenger:failed:retry` le fait avancer.");
        $this->comment('COLUMN messenger_failed.delivered_at', "Instant ou un worker a commence a traiter ce message. NULL tant qu'aucune tentative de rejeu n'a ete lancee.");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_failed');
    }

    /** COMMENT ON n'accepte pas de parametre lie : ce SQL est entierement litteral, d'ou l'echappement manuel. */
    private function comment(string $target, string $comment): void
    {
        $this->addSql(sprintf("COMMENT ON %s IS '%s'", $target, str_replace("'", "''", $comment)));
    }
}
